### ISSUE TITLE
mgob is not working with mongo 4.4

### ISSUE THREAD

**Issue by front1989** [stefanprodan/mgob#123]
Hello, 
mgob was working fine with the mongo 4.2, but i updated for 4.4 and it stopped to work.
I also update the mgob to 1.2. 

The error
/root $ curl -X POST http://localhost:8090/backup/database
{"error":"mongodump log 2020-10-30T16:34:31.137+0000\tFailed: error creating intents to dump: error creating intents for database config: error counting config.system.indexBuilds: (Unauthorized) not authorized on config to execute command { count: \"system.indexBuilds\", lsid: { id: UUID(\"74bb8d81-3f5c-4071-8a47-9239dd226336\") }, $clusterTime: { clusterTime: Timestamp(1604075661, 1), signature: { hash: BinData(0, 9DE2F8D0093F613FE3BAEEF49BCDE778DA43C31E), keyId: 6846331182976598018 } }, $db: \"config\", $readPreference: { mode: \"primary\" } } : exit status 1"}

The user has root and backup role.
Do you know what is the issue?

**Comment by JuniorCtba** [comment]
The version 1.3 is also not working with mongo 4.4, you need to have the mongodump version 100.2.0

**Comment by downagain** [comment]
@JuniorCtba do you have a workaround for this? It seems there isn't yet a proper binary available.

**Comment by JuniorCtba** [comment]
@downagain, yes i have created a new dockerfile for that

**Comment by xakraz** [comment]
@JuniorCtba Would you be kind enough to share your working setup ? 😇 🙏🏻

**Comment by daulet2030** [comment]
I forked this project and changed Dockerfile like this:
https://github.com/daulet2030/mgob/commit/403bdb90750cefa091eb2e4bec832b9b366d2f5b
it works with mongo v4.4.3, replica set

**Comment by JuniorCtba** [comment]
@xakraz 

#this dockerfile was custom by us, because the official version does not support mongo 4.4
#get the latest version of code here https://github.com/stefanprodan/mgob and use this dockerfile to build
#this one must be tagged as maven2.it.volvo.net:18468/mgob:debian
FROM golang:1.13

ARG VERSION
ENV http_proxy http://cs-ws-s-gdsp-proxy:c6OafP9d@httppxgot.srv.volvo.com:8080
ENV https_proxy http://cs-ws-s-gdsp-proxy:c6OafP9d@httppxgot.srv.volvo.com:8080
ENV no_proxy volvo.com,volvo.net

COPY . /go/src/github.com/stefanprodan/mgob

WORKDIR /go/src/github.com/stefanprodan/mgob

RUN CGO_ENABLED=0 GOOS=linux \
      go build \
        -ldflags "-X main.version=$VERSION" \
        -a -installsuffix cgo \
        -o mgob github.com/stefanprodan/mgob/cmd/mgob

FROM debian:buster
ENV http_proxy http://cs-ws-s-gdsp-proxy:c6OafP9d@httppxgot.srv.volvo.com:8080
ENV https_proxy http://cs-ws-s-gdsp-proxy:c6OafP9d@httppxgot.srv.volvo.com:8080
ENV no_proxy volvo.com,volvo.net,,svc.cluster.local,localhost

RUN apt-get update && apt-get install -y apt-transport-https gnupg curl lsb-release wget unzip

#install the azure cli 
RUN apt-get update && apt-get -y upgrade && \
    apt-get -f -y install curl apt-transport-https lsb-release gnupg python3-pip python-pip && \
    curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/microsoft.asc.gpg && \
    CLI_REPO=$(lsb_release -cs) && \
    echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ ${CLI_REPO} main" \
    > /etc/apt/sources.list.d/azure-cli.list && \
    apt-get update && \
    apt-get install -y azure-cli && \
    rm -rf /var/lib/apt/lists/*

#gcloud
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl --insecure https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && apt-get update -y && apt-get install google-cloud-sdk -y

# Install mongodb
RUN wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add -
RUN echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 main" |  tee /etc/apt/sources.list.d/mongodb-org-4.4.list
RUN apt-get update
RUN apt-get install -y mongodb-org-tools

ADD https://dl.minio.io/client/mc/release/linux-amd64/mc /usr/bin
RUN chmod u+x /usr/bin/mc

ADD https://downloads.rclone.org/rclone-current-linux-amd64.zip /tmp
RUN cd /tmp \
  && unzip rclone-current-linux-amd64.zip \
  && cp rclone-*-linux-amd64/rclone /usr/bin/ \
  && chmod u+x /usr/bin/rclone

WORKDIR /root/

COPY --from=0 /go/src/github.com/stefanprodan/mgob/mgob .

VOLUME ["/config", "/storage", "/tmp", "/data"]

ENTRYPOINT [ "./mgob" ]

**Comment by JuniorCtba** [comment]
@xakraz 

#this dockerfile was custom by us, because the official version does not support mongo 4.4
#get the latest version of code here https://github.com/stefanprodan/mgob and use this dockerfile to build

FROM golang:1.13

ARG VERSION
ENV http_proxy xxxx
ENV https_proxy xxxxx
ENV xxxxx

COPY . /go/src/github.com/stefanprodan/mgob

WORKDIR /go/src/github.com/stefanprodan/mgob

RUN CGO_ENABLED=0 GOOS=linux \
      go build \
        -ldflags "-X main.version=$VERSION" \
        -a -installsuffix cgo \
        -o mgob github.com/stefanprodan/mgob/cmd/mgob

FROM debian:buster
ENV http_proxy xxxx
ENV https_proxy xxxxx
ENV no_proxy xxxxx

RUN apt-get update && apt-get install -y apt-transport-https gnupg curl lsb-release wget unzip

#install the azure cli 
RUN apt-get update && apt-get -y upgrade && \
    apt-get -f -y install curl apt-transport-https lsb-release gnupg python3-pip python-pip && \
    curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/microsoft.asc.gpg && \
    CLI_REPO=$(lsb_release -cs) && \
    echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ ${CLI_REPO} main" \
    > /etc/apt/sources.list.d/azure-cli.list && \
    apt-get update && \
    apt-get install -y azure-cli && \
    rm -rf /var/lib/apt/lists/*

#gcloud
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl --insecure https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && apt-get update -y && apt-get install google-cloud-sdk -y

# Install mongodb
RUN wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add -
RUN echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 main" |  tee /etc/apt/sources.list.d/mongodb-org-4.4.list
RUN apt-get update
RUN apt-get install -y mongodb-org-tools

ADD https://dl.minio.io/client/mc/release/linux-amd64/mc /usr/bin
RUN chmod u+x /usr/bin/mc

ADD https://downloads.rclone.org/rclone-current-linux-amd64.zip /tmp
RUN cd /tmp \
  && unzip rclone-current-linux-amd64.zip \
  && cp rclone-*-linux-amd64/rclone /usr/bin/ \
  && chmod u+x /usr/bin/rclone

WORKDIR /root/

COPY --from=0 /go/src/github.com/stefanprodan/mgob/mgob .

VOLUME ["/config", "/storage", "/tmp", "/data"]

ENTRYPOINT [ "./mgob" ]

**Comment by xakraz** [comment]
Thanks both of you @daulet2030 and @JuniorCtba 

🤔 Strange, We have running:
* MongoDB 4.4.3
* Mgob 1.3

And it works ...

**Comment by vassie79** [comment]
I'm having the same issue backing up our Atlas hosted cluster

As we run an M50 cluster we had to disable the legacy backup option and enable cloud backup when upgrading to 4.4, I'm not sure if this is related, the error message from the Kubernetes pod is below:

```
{"error":"mongodump log 2021-02-03T11:08:20.351+0000\tWARNING: ignoring unsupported URI parameter 'replicaset' 2021-02-03T11:08:25.242+0000\tFailed: error creating intents to dump: error creating intents for database config: error counting config.system.indexBuilds: (Unauthorized) not authorized on config to execute command { count: \"system.indexBuilds\", lsid: { id: UUID(\"2a7851fa-a819-4b58-8150-0715113ed32f\") }, $clusterTime: { clusterTime: Timestamp(1612350499, 2), signature: { hash: BinData(0, E68B9D751E88FAA6B387FC5DC36F9CBAAD64D956), keyId: 6888349002652188673 } }, $db: \"config\", $readPreference: { mode: \"primary\" } } : exit status 1"}
```

**Comment by xakraz** [comment]
🤔
* I am using the "defaut" image `stefanprodan/mgob:1.3`
* I am using an Atlas `M10` cluster with 3 replicasets and Cloud Backup + "Continuous Cloud Backup"
* The Atlas cluster is running Mongo 4.4.3
* I am using the URI format `mongo+srv`
* My user has the MongoDB role `backup@admin`

And it works ...

**Comment by vassie79** [comment]
> 🤔
> 
> * I am using the "defaut" image `stefanprodan/mgob:1.3`
> * I am using an Atlas `M10` cluster with 3 replicasets and Cloud Backup + "Continuous Cloud Backup"
> * The Atlas cluster is running Mongo 4.4.3
> * I am using the URI format `mongo+srv`
> * My user has the MongoDB role `backup@admin`
> 
> And it works ...

Do you have a full example? I still cannot get it to work.

**Comment by alexcurtin** [comment]
I got this working after running into the same problem, by using the latest version of mongo-tools https://github.com/mongodb/mongo-tools/releases/tag/100.3.1 in the dockerfile, heres the important changes to get the same dockerfile to work (alpine was difficult to build the mongo tool binaries for musl linux)

``` diff
diff --git a/Dockerfile b/Dockerfile
index 5ce00b7..9a63f8d 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,4 +1,4 @@
-FROM golang:1.15
+FROM golang:1.15 as builder
 
 ARG VERSION
 
@@ -7,10 +7,17 @@ COPY . /go/src/github.com/stefanprodan/mgob
 WORKDIR /go/src/github.com/stefanprodan/mgob
 
 RUN CGO_ENABLED=0 GOOS=linux \
-      go build \
-        -ldflags "-X main.version=$VERSION" \
-        -a -installsuffix cgo \
-        -o mgob github.com/stefanprodan/mgob/cmd/mgob
+  go build \
+  -ldflags "-X main.version=$VERSION" \
+  -a -installsuffix cgo \
+  -o mgob github.com/stefanprodan/mgob/cmd/mgob
+
+FROM golang:1.15-alpine3.12 as builder2
+
+RUN apk add --no-cache git build-base krb5-dev
+RUN git clone https://github.com/mongodb/mongo-tools.git
+WORKDIR mongo-tools
+RUN ./make build
 
 FROM alpine:3.12
 
@@ -18,7 +25,7 @@ ARG BUILD_DATE
 ARG VCS_REF
 ARG VERSION
 
-ENV MONGODB_TOOLS_VERSION 4.2.3-r1
 ENV GNUPG_VERSION 2.2.23-r0
 ENV GOOGLE_CLOUD_SDK_VERSION 316.0.0
 ENV AZURE_CLI_VERSION 2.13.0
@@ -26,16 +33,16 @@ ENV AWS_CLI_VERSION 1.18.159
 ENV PATH /root/google-cloud-sdk/bin:$PATH
 
 LABEL org.label-schema.build-date=$BUILD_DATE \
-      org.label-schema.name="mgob" \
-      org.label-schema.description="MongoDB backup automation tool" \
-      org.label-schema.url="https://github.com/stefanprodan/mgob" \
-      org.label-schema.vcs-ref=$VCS_REF \
-      org.label-schema.vcs-url="https://github.com/stefanprodan/mgob" \
-      org.label-schema.vendor="stefanprodan.com" \
-      org.label-schema.version=$VERSION \
-      org.label-schema.schema-version="1.0"
-
-RUN apk add --no-cache ca-certificates tzdata mongodb-tools=${MONGODB_TOOLS_VERSION} gnupg=${GNUPG_VERSION}
+  org.label-schema.name="mgob" \
+  org.label-schema.description="MongoDB backup automation tool" \
+  org.label-schema.url="https://github.com/stefanprodan/mgob" \
+  org.label-schema.vcs-ref=$VCS_REF \
+  org.label-schema.vcs-url="https://github.com/stefanprodan/mgob" \
+  org.label-schema.vendor="stefanprodan.com" \
+  org.label-schema.version=$VERSION \
+  org.label-schema.schema-version="1.0"
+
+RUN apk add --no-cache ca-certificates tzdata gnupg=${GNUPG_VERSION}
 ADD https://dl.minio.io/client/mc/release/linux-amd64/mc /usr/bin
 RUN chmod u+x /usr/bin/mc
 
@@ -50,24 +57,26 @@ WORKDIR /root/
 #install gcloud
 # https://github.com/GoogleCloudPlatform/cloud-sdk-docker/blob/69b7b0031d877600a9146c1111e43bc66b536de7/alpine/Dockerfile
 RUN apk --no-cache add \
-        curl \
-        python3 \
-        py3-pip \
-        bash \
-        libc6-compat \
-        openssh-client \
-        git \
-    && pip3 --no-cache-dir install --upgrade pip && \
-    pip --no-cache-dir install wheel && \
-    pip --no-cache-dir install crcmod && \
-    curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${GOOGLE_CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
-    tar xzf google-cloud-sdk-${GOOGLE_CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
-    rm google-cloud-sdk-${GOOGLE_CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
-    ln -s /lib /lib64 && \
-    gcloud config set core/disable_usage_reporting true && \
-    gcloud config set component_manager/disable_update_check true && \
-    gcloud config set metrics/environment github_docker_image && \
-    gcloud --version
+  curl \
+  build-base \
+  krb5-dev \
+  python3 \
+  py3-pip \
+  bash \
+  libc6-compat \
+  openssh-client \
+  git \
+  && pip3 --no-cache-dir install --upgrade pip && \
+  pip --no-cache-dir install wheel && \
+  pip --no-cache-dir install crcmod && \
+  curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${GOOGLE_CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
+  tar xzf google-cloud-sdk-${GOOGLE_CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
+  rm google-cloud-sdk-${GOOGLE_CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
+  ln -s /lib /lib64 && \
+  gcloud config set core/disable_usage_reporting true && \
+  gcloud config set component_manager/disable_update_check true && \
+  gcloud config set metrics/environment github_docker_image && \
+  gcloud --version
 
 # install azure-cli and aws-cli
 RUN apk --no-cache add --virtual=build gcc libffi-dev musl-dev openssl-dev python3-dev make && \
@@ -76,7 +85,8 @@ RUN apk --no-cache add --virtual=build gcc libffi-dev musl-dev openssl-dev pytho
   pip --no-cache-dir install awscli==${AWS_CLI_VERSION} && \
   apk del --purge build
 
-COPY --from=0 /go/src/github.com/stefanprodan/mgob/mgob .
+COPY --from=builder /go/src/github.com/stefanprodan/mgob/mgob .
+COPY --from=builder2 /go/mongo-tools/bin/* /usr/bin
 
 VOLUME ["/config", "/storage", "/tmp", "/data"]
 
```

**Comment by ngeorgakopoulos-deloitte** [comment]
@stefanprodan can you build and upload an image with the latest version to https://hub.docker.com/r/stefanprodan/mgob/ ?

**Comment by nicolas-g** [comment]
@stefanprodan can you build and upload an image with the latest version to https://hub.docker.com/r/stefanprodan/mgob/ ?
