### ISSUE TITLE
Remote renention?

### ISSUE THREAD

**Issue by wclr** [stefanprodan/mgob#57]
Do you plan to add remote retention? Or it is not so needed in your view?

**Comment by dottodot** [comment]
Think this would be a good addition as storing unnecessary backups could result in unnecessary costs.

**Comment by rafta-mask** [comment]
+1
It would be very useful.

**Comment by DoubleHub** [comment]
+1
It would be very helpful, to avoid extra costs for storage

**Comment by vingrad** [comment]
+1

**Comment by vingrad** [comment]
+1

**Comment by bryht** [comment]
date=\`date -d @$(($(date '+%s')-86400*$MONGODB_BACKUP_RETENTION_DAYS)) '+%Y-%m-%dT%H:%MZ'\`
az storage blob delete-batch -s $MONGODB_BACKUP_AZURE_BLOB_STORAGE_CONTAINER --pattern *.gz --if-unmodified-since $date --connection-string $MONGODB_BACKUP_AZURE_BLOB_STORAGE_CONNECTION_STRING

I added this script inside docker as a cronjob to clean azure expired files
